---
# peergos-version: v1.17.0-12-gf44b3dbe
name: peergos
base: core24
adopt-info: peergos-webui
summary: A p2p, secure file storage, social network and application protocol
description: |
  Peergos is building the next web - the private web, where end users are
  in control. Imagine web apps being secure by default and unable to track
  you. Imagine being able to control exactly what personal data each web
  app can see. Imagine never having to log in to an app ever again. You own
  your data and decide where it is stored and who can see it. At Peergos,
  we believe that privacy is a fundamental human right and we want to make
  it easy for everyone to interact online in ways that respect this right.

  The foundation of Peergos is a peer-to-peer encrypted global filesystem
  with fine-grained access control designed to be resistant to surveillance
  of data content or friendship graphs. It has a secure messenger, an
  encrypted email client and bridge, and a totally private and secure
  social network, where users are in control of who sees what (executed
  cryptographically). Our motto at Peergos is, "Control your data, control
  your destiny."

  The name Peergos comes from the Greek word Πύργος (Pyrgos), which means
  stronghold or tower, but phonetically spelt with the nice connection to
  being peer-to-peer. Pronunciation: peer-goss (as in gossip).

contact: https://peergos.org/contact
issues:
  - https://github.com/rapenne-s/snap-peergos/issues
  - https://github.com/Peergos/web-ui/issues
source-code:
  - https://github.com/rapenne-s/snap-peergos
  - https://github.com/Peergos/web-ui
website: https://peergos.org

grade: stable
confinement: strict
compression: lzo

parts:

  # script to run java
  startup:
    plugin: dump
    source: ./snap/local
    source-type: local

  # actual program
  peergos-webui:
    plugin: ant
    build-packages:
      - ant
      - openjdk-21-jdk
    stage-packages:
      - default-jre
    ant-build-targets:
      - dist
    source-type: git
    source: https://github.com/peergos/web-ui
    override-build: |
      craftctl default

      # define version
      GIT_VERSION="$(git rev-parse HEAD)"
      VERSION="$(git describe --tags $GIT_VERSION)"
      craftctl set version="$VERSION"

      # workaround because ant plugin is copying all jar files found
      find "${CRAFT_PART_INSTALL}/jar" -name '*.jar' -delete
      install "${CRAFT_PART_BUILD}/server/Peergos.jar" "${CRAFT_PART_INSTALL}/jar/Peergos.jar"

platforms:
  amd64:
  arm64:

apps:
  peergos:
    command: usr/bin/peergos
    plugs:
      - desktop
      - home
      - removable-media
      - network
      - network-bind

lint:
  ignore:
    - library
